### PR TITLE
Introduce changes against ruby 3.1

### PR DESCRIPTION
**Pull request by szymonlipkaaa**
Since Ruby 3.1 default behavior of method #load on YAML is aliased to #safe_load, and this method doesn't allow aliases in the YAML by default. We need to add aliases: true to bring back aliases.

### CODE REVIEW

**Comment by knapo** [comment]
hey @szymonlipkaaa ! thanks for submitting the PR and testing against ruby 3.1. I changed github workflow to run tests against ruby 3.1 but it looks like I don't use aliases in any of the spec and they pass in 3.1. I'll add some to check that.

**Review by knapo — CHANGES_REQUESTED** [review]

**Comment by knapo** [comment]
I [added yml alias](https://github.com/knapo/a9n/commit/3255b3ef96356b0cf04ebff854cc2c8953960151) to test files to it's covered by specs

**Comment by szymonlipkaaa** [comment]
@knapo since we want to support other versions of ruby I need to put some ugly if into code, because before 3.1 YML.load wasn't accepting `aliases: true` unfortunately

**Comment by knapo** [comment]
yeap, it needs a bit of ugliness. I already did that in https://github.com/knapo/a9n/commit/ecfaaf41d57ea6786e73c1367d56fc2b46007c7d#diff-21b28a86cd66067badcbd82129c7302f254a3849adf1038ce3590a8f2830e45eR4 and released a new version with 3.1 support 🚀

**Pull request merged**
